# Generated by Django 6.1 on 2026-09-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_product_color_product_material_product_model_mpn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_mpn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='alternative_suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='extracted_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending AI Classification'), ('PROCESSING', 'AI is Processing'), ('COMPLETED', 'Classification Complete'), ('MANUAL_REVIEW', 'Needs Manual Review'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=50),
        ),
    ]
