# Generated by Django 6.1.1 on 2026-09-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_remove_product_color_remove_product_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='alternative_suggestions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='predicted_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending AI Classification'), ('PROCESSING', 'AI is Processing'), ('COMPLETED', 'Classification Complete'), ('MANUAL_REVIEW', 'Needs Manual Review'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('alternative_suggestions', models.JSONField(blank=True, null=True)),
                ('extracted_attributes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='classifier.productfamily'),
        ),
    ]
