# Generated by Django 6.1.1 on 2026-09-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_remove_product_alternative_suggestions_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
    ]
