from django.urls import path
from .views import (
    ImportExcelAPIView,
    ProductListAPIView,
    ProductFamilyListAPIView,
    AnalyzeFamilyAPIView,
    MainCategoryListAPIView,
    ReviewListAPIView,
    ProductUpdateAPIView,
    ProductStatsAPIView,
    PauseProcessingAPIView,
    ResumeProcessingAPIView,
    FamilyDetailAPIView,
    ProductDetailAPIView,
    CategorySearchAPIView,
    CategoryWayfindAPIView,
    BrandListAPIView,
    BrandDetailAPIView,
    ClearDataAPIView
)

urlpatterns = [
    path('products/import/', ImportExcelAPIView.as_view(), name='import_excel'),
    path('products/', ProductListAPIView.as_view(), name='product_list'),
    path('families/', ProductFamilyListAPIView.as_view(), name='family_list'),
    path('families/<int:pk>/', FamilyDetailAPIView.as_view(), name='family_detail'),
    path('families/<int:pk>/analyze/', AnalyzeFamilyAPIView.as_view(), name='family_analyze'),
    path('products/<int:pk>/detail/', ProductDetailAPIView.as_view(), name='product_detail'),
    path('products/review/', ReviewListAPIView.as_view(), name='review_list'),
    path('products/<int:pk>/', ProductUpdateAPIView.as_view(), name='product_update'),
    path('products/stats/', ProductStatsAPIView.as_view(), name='product_stats'),
    path('products/clear/', ClearDataAPIView.as_view(), name='clear_data'),
    path('brands/', BrandListAPIView.as_view(), name='brand_list'),
    path('brands/detail/', BrandDetailAPIView.as_view(), name='brand_detail'),
    path('categories/main/', MainCategoryListAPIView.as_view(), name='main_categories'),
    path('categories/search/', CategorySearchAPIView.as_view(), name='category_search'),
    path('categories/wayfind/', CategoryWayfindAPIView.as_view(), name='category_wayfind'),
    path('categories/<str:pk>/wayfind/', CategoryWayfindAPIView.as_view(), name='category_wayfind_detail'),
    path('products/pause/', PauseProcessingAPIView.as_view(), name='pause_processing'),
    path('products/resume/', ResumeProcessingAPIView.as_view(), name='resume_processing'),
]