upstream django_app {
    # 'web' is the name of our Django container in docker-compose
    server web:8000;
}

server {
    listen 80;

    # Allow large file uploads (e.g., 50MB)
    client_max_body_size 50M;

    # Pass all API and website traffic to Django
    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # (In the future, you would serve static CSS/Images from here!)
}